kind: pipeline
type: docker
name: default

steps:
- name: my-docker
  image: node
  commands:
  - |
    chmod +x docker-install.sh
    ./docker-install.sh
    pwd
    ls /var/run
    echo $?
    docker ps

trigger:
  branch:
  - main