# ---
# kind: pipeline
# name: default

# steps:
# - name: write
#   image: ubuntu
#   commands:
#   - touch foo.txt
#   - echo "trying some texts" > foo.txt


# - name: read
#   image: ubuntu
#   commands:
#   - cat foo.txt

---
kind: pipeline
type: docker in docker

steps:
- name: testing docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - |
    docker ps
  privileged: true

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

# steps:
# - name: greeting 
#   commands:
#   - echo hello world
# steps:
# - name: my-docker
#   image: docker
#   commands:
#   - |
    # apt install npm
    # echo check node version
    # node --version
    # echo
    # echo install docker 
    # chmod +x docker-install.sh
    # ./docker-install.sh
    # echo
    # echo check docker version
    # docker --version
    # pwd
    # ls /var/run
    # echo $?
    # docker ps
    # volume:
    # - /var/run/docker.sock:/var/run/docker.sock
  
# trigger:
#   branch:
#   - main