kind: pipeline
type: docker
name: default

steps:
- name: my-docker
  image: ubuntu
  commands:
  - |
    # echo check node version
    # node --version
    # echo
    echo install docker 
    chmod +x docker-install.sh
    ./docker-install.sh
    echo
    echo check docker version
    docker --version
    pwd
    ls /var/run
    echo $?
    docker ps

trigger:
  branch:
  - main