---
kind: pipeline
name: default

steps:
- name: foo
  image: alpine:3.8
  commands:
  - touch foo.txt

- name: bar
  image: alpine:3.8
  commands:
  - ls foo.txt

# ---
# kind: pipeline
# type: exec
# name: default

# steps:
# - name: Running Catus
#   image: docker:dind
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
#   commands:
#   - |
#       echo running and populating the BDD
#       make -f cortex.mk database_pg_full
#       echo
#       echo runnig Cortex on insecure mode
#       make -f cortex.mk run_build_insecure
#   privileged: true

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock

# steps:
# - name: greeting 
#   commands:
#   - echo hello world
# steps:
# - name: my-docker
#   image: docker
#   commands:
#   - |
    # apt install npm
    # echo check node version
    # node --version
    # echo
    # echo install docker 
    # chmod +x docker-install.sh
    # ./docker-install.sh
    # echo
    # echo check docker version
    # docker --version
    # pwd
    # ls /var/run
    # echo $?
    # docker ps
    # volume:
    # - /var/run/docker.sock:/var/run/docker.sock
  
# trigger:
#   branch:
#   - main